const applications = [
  {
    id: 1,
    requestId: 1,
    firstName: 'Jane',
    lastName: 'Doe',
    phone: '+380 93 123 45 67',
    help: '100',
    approved: false,
    status: '',
  },
  {
    id: 2,
    requestId: 1,
    firstName: 'Joan',
    lastName: 'Doe',
    phone: '+380 93 76 54 321',
    help: '300',
    approved: true,
    status: 'in_progress',
  },
  {
    id: 3,
    requestId: 1,
    firstName: 'Jane',
    lastName: 'Doe',
    phone: '+380 93 123 45 67',
    help: '100',
    approved: false,
    status: '',
  },
  {
    id: 4,
    requestId: 1,
    firstName: 'Joan',
    lastName: 'Doe',
    phone: '+380 93 76 54 321',
    help: '300',
    approved: true,
    status: 'in_progress',
  },
  {
    id: 5,
    requestId: 1,
    firstName: 'Jane',
    lastName: 'Doe',
    phone: '+380 93 123 45 67',
    help: '100',
    approved: false,
    status: '',
  },
  {
    id: 6,
    requestId: 1,
    firstName: 'Joan',
    lastName: 'Doe',
    phone: '+380 93 76 54 321',
    help: '300',
    approved: true,
    status: 'in_progress',
  },
  {
    id: 7,
    requestId: 1,
    firstName: 'Jane',
    lastName: 'Doe',
    phone: '+380 93 123 45 67',
    help: '100',
    approved: false,
    status: '',
  },
  {
    id: 8,
    requestId: 1,
    firstName: 'Joan',
    lastName: 'Doe',
    phone: '+380 93 76 54 321',
    help: '300',
    approved: true,
    status: 'in_progress',
  },
  {
    id: 9,
    requestId: 1,
    firstName: 'Jane',
    lastName: 'Doe',
    phone: '+380 93 123 45 67',
    help: '100',
    approved: false,
    status: '',
  },
  {
    id: 10,
    requestId: 1,
    firstName: 'Joan',
    lastName: 'Doe',
    phone: '+380 93 76 54 321',
    help: '300',
    approved: true,
    status: 'in_progress',
  },
  {
    id: 11,
    requestId: 1,
    firstName: 'Jane',
    lastName: 'Doe',
    phone: '+380 93 123 45 67',
    help: '100',
    approved: false,
    status: '',
  },
  {
    id: 12,
    requestId: 1,
    firstName: 'Joan',
    lastName: 'Doe',
    phone: '+380 93 76 54 321',
    help: '300',
    approved: true,
    status: 'in_progress',
  },
];

export default applications;
